// src/lib/components/Seo.svelte
<script>
  import { page } from "$app/stores"
  import { dev, prerendering } from "$app/env"

  const baseUrl = "https://www.honai.me"

  export let title = "Honai Ueoka"
  export let description = ""
  export let path = ""
  export let ogImage = ""

  const ogImageUrl = ogImage
    ? ogImage.startsWith("/")
      ? `${baseUrl}${ogImage}`
      : ogImage
    : `${baseUrl}/images/profile.png`
  const largeCard = !!ogImage

  if ((dev || prerendering) && !path) {
    console.info("Path is not set on Seo props")
    console.info("Using path from $page", $page.path)
    path = $page.path
  }

  const canonicalUrl = `${baseUrl}${path}`
</script>

<svelte:head>
  <link rel="canonical" href={canonicalUrl} />
  <title>{title}</title>
  <meta name="description" content={description} />

  <meta property="og:url" content={canonicalUrl} />
  <meta property="og:title" content={title} />
  <meta property="og:description" content={description} />
  <meta property="og:image" content={ogImageUrl} />
  <meta property="fb:app_id" content="1144529745735811" />
  <meta property="og:locale" content="ja_JP" />

  <meta name="twitter:card" content={largeCard ? "summary_large_image" : "summary"} />
  <meta name="twitter:creator" content="@_honai" />
</svelte:head>

// src/_includes/Seo.jsx
/**
 * @param {object} props
 * @param {string} props.title
 * @param {string} props.pageUrl
 * @param {string} props.description
 * @param {string} [props.og_image_url]
 * @param {boolean} [props.large_card]
 */
export const Seo = ({
  title,
  pageUrl,
  description,
  og_image_url,
  large_card,
}) => {
  if (!pageUrl.startsWith("/")) {
    throw new Error("Invalid pageUrl");
  }
  const canonicalUrl = `https://www.honai.me${pageUrl}`;
  const ogImage = og_image_url || "https://www.honai.me/images/profile.png";
  return (
    <>
      <meta charSet="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <link rel="canonical" href={canonicalUrl} />
      <title>{title}</title>
      {!!description && <meta name="description" content={description} />}

      <meta property="og:url" content={canonicalUrl} />
      <meta property="og:title" content={title} />
      {!!description && (
        <meta property="og:description" content={description} />
      )}
      <meta property="og:image" content={ogImage} />
      <meta property="fb:app_id" content="1144529745735811" />
      <meta property="og:locale" content="ja_JP" />

      <meta
        name="twitter:card"
        content={large_card ? "summary_large_image" : "summary"}
      />
      <meta name="twitter:site" content="@_honai" />

      <link rel="icon" href="/favicon.ico" />
    </>
  );
};
