// src/_includes/BlogPost.svelte
<script>
  import BlogHeader from "./BlogHeader.svelte";
  import BlogLayout from "./BlogLayout.svelte";
  import { getJsFuncs } from "./SvelteContext.svelte";
  import Footer from "./Footer.svelte";
  import Script from "./Script.svelte";

  const githubLinkBase = "https://github.com/honai/honai.me/blob/main/";
  const styleSheets = [
    {
      href: "https://cdnjs.cloudflare.com/ajax/libs/prism/1.20.0/themes/prism-tomorrow.min.css",
      integrity: "sha256-xevuwyBEb2ZYh4nDhj0g3Z/rDBnM569hg9Vq6gEw/Sg=",
    },
    {
      href: "https://cdn.jsdelivr.net/npm/katex@0.12.0/dist/katex.min.css",
      integrity:
        "sha384-AfEj0r4/OFrOo5t7NnNe46zW/tFgW6x/bCJG8FqQCEo3+Aro6EYUG4+cU+KJWu/X",
      async: true,
    },
  ];

  export let content;
  export let page;
  export let collections;
  export let title;
  export let description;
  export let og_image_url;
  export let updated;
  export let plugins;
  const fn = getJsFuncs();
  const newerPost = fn.getPreviousCollectionItem(collections.posts, page);
  const olderPost = fn.getNextCollectionItem(collections.posts, page);
</script>

<BlogLayout
  pageUrl={page.url}
  {title}
  {description}
  ogImageUrl={og_image_url}
  {styleSheets}
>
  <div class="body-layout">
    <BlogHeader />
    <div class="grow">
      <article class="article-layout">
        <header class="header article-header">
          <h1 class="title">{title}</h1>
          <div class="meta">
            <div class="century-gothic date">
              <time id="published-time" dateTime={fn.isodate(page.date)}>
                {fn.isodate(page.date)}
              </time>
              {#if updated}
                {" "}
                (Updated at{" "}
                <time id="updated-time" dateTime={fn.isodate(updated)}>
                  {updated}
                </time>
                )
              {/if}
            </div>
          </div>
        </header>

        <aside class="aside">
          <div class="sticky">
            <div class="post-toc">
              <div class="title">目次</div>
              <!-- nav.toc > ol > li > a.-active -->
              {@html fn.toc(content)}
            </div>

            <div class="post-navigate">
              <div>
                <a href="/blog">記事一覧</a>
              </div>
              {#if newerPost}
                <div>
                  次の記事:{" "}
                  <a href={newerPost.url}>{newerPost.data.title}</a>
                </div>
              {/if}
              {#if olderPost}
                <div>
                  前の記事:{" "}
                  <a href={olderPost.url}>{olderPost.data.title}</a>
                </div>
              {/if}
            </div>

            <div class="post-edit">
              <a href={`${githubLinkBase}${page.inputPath}`} class="link">
                この記事の編集をリクエスト (GitHub)
              </a>
            </div>
          </div>
        </aside>

        <main class="main">
          <div class="post-markdown">
            {@html content}
          </div>
          >
        </main>

        <div class="ad ad-sense">
          <!-- 記事の下 -->
          <ins
            class="adsbygoogle"
            style="display:block"
            data-ad-client="ca-pub-9155380222623167"
            data-ad-slot="4880052047"
            data-ad-format="auto"
            data-full-width-responsive="true"
          />
        </div>
      </article>
    </div>
    <Footer />
  </div>
</BlogLayout>
<Script defer src="/scripts/blog-post.js" />
{#if plugins.includes("twitter")}
  <Script
    type="application/json"
    className="external-scripts-list"
    js={`
        ["https://platform.twitter.com/widgets.js"]
      `}
  />
{/if}

// src/_includes/layouts/BlogPost.tsx
import { useEleventy } from "../EleventyContext.js";
import { Footer } from "../components/Footer.js";
import { Script } from "../components/Script.js";
import { ArticleHeader } from "../components/blog/ArticleHeader.js";
import { css, uc } from "../style.js";
import { PostMd } from "../components/blog/PostMd.js";
import { Toc } from "../components/blog/Toc.js";
import { PostNavigate } from "../components/blog/PostNavigate.js";
import { BaseHtml } from "./BaseHtml.js";
import { Header } from "../components/Header.js";
import VerticalGrow from "../components/VerticalGrow.js";
import {
  TwitterShareIcon,
  TwitterShareLink,
} from "../components/TwitterShare.js";
import { Post } from "../../blog/post/posts.js";

const githubLinkBase = "https://github.com/honai/honai.me/blob/main/";

interface Props {
  post: Post;
  newerPost?: Post;
  olderPost?: Post;
}

export default ({ post, newerPost, olderPost }: Props) => {
  const fn = useEleventy();
  const { title, description, thumbnail_url, updated, date, content } = post;
  const url = `/blog/post/${post.slug}/`;
  return (
    <BaseHtml
      title={title}
      description={description}
      thumbnailUrl={thumbnail_url || "/images/profile.png"}
      twitterCard={thumbnail_url ? { kind: "large" } : { kind: "normal" }}
      lazyStylesheets={[
        "/styles/prism-tomorrow.min.css",
        "https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.min.css",
      ]}
    >
      <VerticalGrow>
        <Header maxWidth="120rem" />
        <VerticalGrow.Grow>
          <article class={articleLayout()}>
            <div class="header">
              <ArticleHeader
                title={title}
                published={fn.isodate(date)}
                updated={updated ? fn.isodate(updated) : undefined}
              />
            </div>
            <aside class="aside">
              <div class="sticky">
                <Toc tocHtml={"TODO"} />
                <div class={css({ color: "$textSecondary" })()}>
                  <a
                    href={`${githubLinkBase}/src/blog/post/${post.slug}.md`}
                    class={uc.uncolor}
                  >
                    この記事の編集をリクエスト (GitHub)
                  </a>
                  <br />
                  <TwitterShareLink path={url} title={title}>
                    ツイート
                  </TwitterShareLink>
                </div>
                <PostNavigate newerPost={newerPost} olderPost={olderPost} />
              </div>
            </aside>
            <div className="main">
              <main>
                <PostMd content={content} />
              </main>
            </div>
          </article>
          <div class={css({ textAlign: "center", marginBlockStart: "0rem" })()}>
            <TwitterShareIcon path={url} title={title} />
          </div>
          <Footer />
        </VerticalGrow.Grow>
      </VerticalGrow>
      {post.plugins && post.plugins.includes("twitter") && (
        <Script type="application/json" class="external-scripts-list">{`
          ["https://platform.twitter.com/widgets.js"]
        `}</Script>
      )}
      <script type="module" src="/js/post-page.js"></script>
    </BaseHtml>
  );
};

const articleLayout = css({
  // FIXME: class直書き指定をやめる
  padding: "1rem",
  "& > .aside": {
    maxHeight: "50vh",
    overflowY: "auto",
    border: "1px solid $border",
  },
  "@md": {
    display: "grid",
    gridTemplateAreas: `"header header"
                        "main   aside"`,
    maxWidth: "120rem",
    margin: "0 auto",
    gridTemplateColumns: "minmax(0, 1fr) min(30rem, 30vw)",
    gridTemplateRows: "18rem auto",
    padding: "2rem 3rem",
    gap: "2rem 6rem",
    "> .header": { gridArea: "header", maxWidth: "72rem", margin: "auto" },
    "> .aside": {
      gridArea: "aside",
      maxHeight: "unset",
      border: "none",
      overflowY: "visible",
    },
    "> .main": { gridArea: "main" },
    "> .aside > .sticky": {
      position: "sticky",
      top: "2rem",
      display: "flex",
      flexDirection: "column",
      gap: "2rem",
      maxHeight: "calc(100vh - 4rem)",
      overflowY: "auto",
    },
  },
});
