// src/_includes/BlogLayout.svelte
<script>
  import Script from "./Script.svelte";
  import Seo from "./Seo.svelte";

  export let pageUrl;
  export let title;
  export let description;
  /** @type {{href: string, integrity: string, async?: boolean}[]} */
  export let styleSheets = [];
  export let ogImageUrl = null;
</script>

<svelte:head>
  <base href={pageUrl} />
  {#each styleSheets as { href, integrity, async }}
    {#if async}
      <link
        rel="preload"
        as="style"
        {href}
        {integrity}
        crossOrigin="anonymous"
        onload="this.rel='stylesheet';"
      />
    {:else}
      <link rel="stylesheet" {href} {integrity} crossOrigin="anonymous" />
    {/if}
  {/each}
  <!-- TODO: async fallback -->
  <link
    rel="stylesheet"
    href="https://use.typekit.net/bdo3rru.css"
    media="print"
    onload="this.media='all'"
  />
  <link rel="stylesheet" href="/blog.css" />
</svelte:head>
<Seo {pageUrl} {title} {description} {ogImageUrl} />

<slot />

<Script
  type="application/json"
  className="external-scripts-list"
  js={`
    [
      "https://www.google-analytics.com/analytics.js",
      "https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9155380222623167"
    ]
  `}
/>
<Script
  js={`
    // polyfill
    if (!window.requestIdleCallback) {
      window.requestIdleCallback = (cb) => {
        window.setTimeout(cb, 1)
      }
    }
    window.requestIdleCallback(() => {
      const elms = document.getElementsByClassName('external-scripts-list')
      const scripts = Array.from(elms).map(e => JSON.parse(e.textContent)).flat()
      scripts.map(s => {
        var e = document.createElement('script')
        e.src = s
        document.body.appendChild(e)
      })
      window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
      ga('create', '{{ gtag_id | safe }}', 'auto');
      ga('send', 'pageview');
      (adsbygoogle = window.adsbygoogle || []).push({});
    })
  `}
/>

// src/_includes/layouts/BlogLayout.jsx
import { Script } from "../components/Script";
import { Seo } from "../components/Seo";
import * as AC from "../components/AvoidCache";

const GTAG_ID = "UA-137251140-3";

/**
 * @typedef {Object} StyleSheet
 * @prop {string} href
 * @prop {string} integrity
 * @prop {boolean} [async]
 */

/**
 * @param {Object} props
 * @param {string} props.pageUrl
 * @param {string} props.title
 * @param {string} props.description
 * @param {StyleSheet[]} [props.styleSheets]
 * @param {string} [props.thumbnailUrl]
 * @param {any} props.children
 */
export const BlogLayout = ({
  pageUrl,
  title,
  description,
  thumbnailUrl,
  styleSheets,
  children,
}) => {
  return (
    <html lang="ja">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width" />
        <Seo
          pageUrl={pageUrl}
          title={title}
          description={description}
          thumbnailUrl={thumbnailUrl}
        />
        <link
          rel="alternate"
          href="/blog/rss.xml"
          type="application/rss+xml"
          title="Honai's Blog"
        />
        {/* 相対画像のため。deprecated */}
        <base href={pageUrl} />
        {(styleSheets || []).map(({ href, integrity, async }) =>
          async ? (
            <link
              rel="preload"
              as="style"
              href={href}
              integrity={integrity}
              crossOrigin="anonymous"
              // @ts-ignore
              onLoad="this.rel='stylesheet';"
            />
          ) : (
            <link
              rel="stylesheet"
              href={href}
              integrity={integrity}
              crossOrigin="anonymous"
            />
          )
        )}
        <link
          rel="stylesheet"
          href="https://use.typekit.net/bdo3rru.css"
          media="print"
          // @ts-ignore
          onload="this.media='all'"
        />
        <AC.Link rel="stylesheet" href="/index.css" />
        <AC.Script type="module" src="/scripts/theme-toggle.js" />
      </head>

      <body>{children}</body>
    </html>
  );
};
