// src/routes/blog/_Header.svelte
<header class="site-header">
  <h1 class="title">
    <a href="/blog/" class="_reset-a">Honai's Blog</a>
  </h1>
</header>

<style lang="scss">
  .site-header {
    height: 5.4rem;
    color: #fff;
    background-color: var(--color-primary);
    border-bottom: 1px solid rgba(0, 0, 0, 0.5);
    display: flex;
    align-items: center;
    justify-content: center;
    > .title {
      font-family: var(--font-family-century);
      font-weight: var(--font-weight-century);
      font-size: 2.4rem;
    }
  }
</style>

// src/components/Header.tsx
import Link from 'next/link'

import { primaryColor } from 'src/components/theme'

const NormalTitle = (): JSX.Element => (
  <>
    <Link href="/">
      <a className="reset">honai.me</a>
    </Link>
    <style jsx>
      {`
        a {
          font-size: 1.2rem;
          color: rgba(255, 255, 255, 0.8);
          padding: 0 10px;
        }
      `}
    </style>
  </>
)

interface ToppageTitleProps {
  isHeroInview?: boolean
}

const ToppageTitle = ({ isHeroInview }: ToppageTitleProps): JSX.Element => (
  <>
    <Link href="/">
      <a className="reset">
        <img src="/static/profile.png" alt="アイコン" height="100%" />
        <span>Honai Ueoka</span>
      </a>
    </Link>
    <style jsx>
      {`
        a {
          align-items: center;
          display: flex;
          padding: 5px;
          height: 36px;
          opacity: ${isHeroInview ? 0 : 1};
          transition: opacity linear 0.1s;
        }
        img {
          border-radius: 50%;
          margin: 0 5px;
        }
      `}
    </style>
  </>
)

const Header = ({ isToppage, isHeroInview }: HeaderProps): JSX.Element => (
  <header className="century-gothic">
    <div>{isToppage ? <ToppageTitle isHeroInview={isHeroInview} /> : <NormalTitle />}</div>
    <nav>
      <ul>
        <li>
          <Link href="/">
            <a className="reset">Home</a>
          </Link>
        </li>
        <li>
          <Link href="/blog">
            <a className="reset">Blog</a>
          </Link>
        </li>
      </ul>
    </nav>
    <style jsx>{`
      header {
        background-color: ${primaryColor};
        width: 100%;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.5);
        display: flex;
        color: #fff;
        align-items: center;
        justify-content: space-between;
        position: sticky;
        top: 0;
        z-index: 200;
      }
      nav ul {
        display: flex;
        justify-content: flex-end;
        margin: 0;
        padding: 0;
        line-height: 1;
      }
      nav li {
        list-style: none;
        cursor: pointer;
        transition: background-color ease 0.2s;
      }
      nav li:hover {
        background-color: rgba(255, 255, 255, 0.3);
      }
      nav a {
        display: block;
        padding: calc((36px - 1rem) / 2) 20px;
      }
    `}</style>
  </header>
)

export interface HeaderProps {
  isToppage?: boolean
  isHeroInview?: boolean
}

export default Header
